ALTER USER wal_reader REPLICATION;
CREATE ROLE replication_group REPLICATION LOGIN;
GRANT REPLICATION_GROUP TO postgres;
GRANT REPLICATION_GROUP TO wal_reader;

CREATE DATABASE delivery;

COMMENT ON DATABASE delivery IS 'База данных сервиса доставки заказов';

\c delivery;

CREATE TABLE IF NOT EXISTS polygons (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE polygons OWNER TO REPLICATION_GROUP;
ALTER TABLE polygons REPLICA IDENTITY FULL;

COMMENT ON TABLE polygons IS 'Зоны доставки (территории обслуживания)';
COMMENT ON COLUMN polygons.id IS 'Уникальный идентификатор полигона';
COMMENT ON COLUMN polygons.name IS 'Название зоны доставки';
COMMENT ON COLUMN polygons.city IS 'Город, к которому относится зона';
COMMENT ON COLUMN polygons.is_active IS 'Активна ли зона доставки';
COMMENT ON COLUMN polygons.created_at IS 'Дата создания полигона';


CREATE TABLE IF NOT EXISTS shops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    delivery_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    start_work_time TIME NOT NULL,
    end_work_time TIME NOT NULL,
    city VARCHAR(100) NOT NULL,
    polygon_id INTEGER,

    CONSTRAINT fk_shops_polygon
        FOREIGN KEY (polygon_id) REFERENCES polygons(id)
        ON DELETE SET NULL
);

ALTER TABLE shops OWNER TO REPLICATION_GROUP;
ALTER TABLE shops REPLICA IDENTITY FULL;

COMMENT ON TABLE shops IS 'Магазины, из которых осуществляется сборка и доставка заказов';
COMMENT ON COLUMN shops.address IS 'Фактический адрес магазина';
COMMENT ON COLUMN shops.delivery_enabled IS 'Включена ли сборка и доставка заказов';
COMMENT ON COLUMN shops.start_work_time IS 'Время начала работы магазина';
COMMENT ON COLUMN shops.end_work_time IS 'Время окончания работы магазина';
COMMENT ON COLUMN shops.polygon_id IS 'Полигон (зона доставки), к которому относится магазин';
COMMENT ON COLUMN shops.city IS 'Город расположения магазина';

CREATE TABLE IF NOT EXISTS couriers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    inn VARCHAR(20) UNIQUE,
    city VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('blocked', 'on_work', 'not_on_work')),
    company VARCHAR(255),
    self_employed BOOLEAN NOT NULL DEFAULT FALSE,
    timezone VARCHAR(50) NOT NULL,
    polygon_id INTEGER,

    CONSTRAINT fk_courier_polygon
        FOREIGN KEY (polygon_id) REFERENCES polygons(id)
        ON DELETE SET NULL
);

ALTER TABLE couriers OWNER TO REPLICATION_GROUP;
ALTER TABLE couriers REPLICA IDENTITY FULL;


COMMENT ON TABLE couriers IS 'Курьеры службы доставки';
COMMENT ON COLUMN couriers.first_name IS 'Имя курьера';
COMMENT ON COLUMN couriers.last_name IS 'Фамилия курьера';
COMMENT ON COLUMN couriers.patronymic IS 'Отчество курьера';
COMMENT ON COLUMN couriers.phone IS 'Контактный телефон (уникальный)';
COMMENT ON COLUMN couriers.email IS 'Email курьера';
COMMENT ON COLUMN couriers.inn IS 'ИНН курьера';
COMMENT ON COLUMN couriers.city IS 'Город работы курьера';
COMMENT ON COLUMN couriers.status IS 'Статус: blocked / on_work / not_on_work';
COMMENT ON COLUMN couriers.company IS 'Курьерская компания';
COMMENT ON COLUMN couriers.self_employed IS 'Является ли курьер самозанятым';
COMMENT ON COLUMN couriers.timezone IS 'Таймзона курьера';
COMMENT ON COLUMN couriers.polygon_id IS 'Зона доставки, в которой работает курьер';

CREATE TABLE IF NOT EXISTS pickers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255),
    status VARCHAR(20) NOT NULL CHECK (status IN ('blocked', 'free', 'busy')),
    network VARCHAR(30) NOT NULL CHECK (network IN ('asx', 'self_delivery', 'otus_logistics')),
    city VARCHAR(100) NOT NULL,
    timezone VARCHAR(50) NOT NULL,
    shop_id INTEGER,

    CONSTRAINT fk_picker_shop
        FOREIGN KEY (shop_id) REFERENCES shops(id)
        ON DELETE SET NULL
);

ALTER TABLE pickers OWNER TO REPLICATION_GROUP;
ALTER TABLE pickers REPLICA IDENTITY FULL;

COMMENT ON TABLE pickers IS 'Сборщики заказов в магазинах';
COMMENT ON COLUMN pickers.status IS 'Статус: blocked / free / busy';
COMMENT ON COLUMN pickers.network IS 'Сеть или подрядчик: asx / self_delivery / otus_logistics';
COMMENT ON COLUMN pickers.shop_id IS 'Магазин, в котором работает сборщик';


CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    amount_type VARCHAR(20) NOT NULL CHECK (amount_type IN ('weight', 'items')),
    price_for_amount_item NUMERIC(10,2) NOT NULL CHECK (price_for_amount_item >= 0),
    date DATE NOT NULL,
    valid_hours INTEGER NOT NULL CHECK (valid_hours >= 0),
    total_amount NUMERIC(10,3) NOT NULL CHECK (total_amount >= 0),
    discount_percent INTEGER DEFAULT 0 CHECK (discount_percent BETWEEN 0 AND 100)
);

ALTER TABLE products OWNER TO REPLICATION_GROUP;
ALTER TABLE products REPLICA IDENTITY FULL;

COMMENT ON TABLE products IS 'Товары магазина';
COMMENT ON COLUMN products.amount_type IS 'Тип измерения: weight (вес) / items (штуки)';
COMMENT ON COLUMN products.price_for_amount_item IS 'Цена за единицу веса или за штуку';
COMMENT ON COLUMN products.date IS 'Дата изготовления товара';
COMMENT ON COLUMN products.valid_hours IS 'Срок годности в часах';
COMMENT ON COLUMN products.total_amount IS 'Общее количество товара в магазине';
COMMENT ON COLUMN products.discount_percent IS 'Процент скидки на товар';


CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (
        status IN ('created', 'collecting', 'collected', 'delivering', 'delivered', 'completed')
    ),
    shop_id INTEGER NOT NULL,
    client_name VARCHAR(255) NOT NULL,
    client_phone VARCHAR(20) NOT NULL,
    client_address VARCHAR(255) NOT NULL,
    picker_id INTEGER,
    courier_id INTEGER,
    payment BOOLEAN NOT NULL DEFAULT FALSE,
    pay_date TIMESTAMP,
    collecting_start_date TIMESTAMP,
    collecting_end_date TIMESTAMP,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    courier_assigned_date TIMESTAMP,
    courier_take_date TIMESTAMP,
    courier_delivered_date TIMESTAMP,
    completed_date TIMESTAMP,

    CONSTRAINT fk_order_shop
        FOREIGN KEY (shop_id) REFERENCES shops(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_order_picker
        FOREIGN KEY (picker_id) REFERENCES pickers(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_order_courier
        FOREIGN KEY (courier_id) REFERENCES couriers(id)
        ON DELETE SET NULL
);

ALTER TABLE orders OWNER TO REPLICATION_GROUP;
ALTER TABLE orders REPLICA IDENTITY FULL;

COMMENT ON TABLE orders IS 'Заказы клиентов';
COMMENT ON COLUMN orders.status IS 'Статус заказа: created → collecting → delivering → completed';
COMMENT ON COLUMN orders.payment IS 'Оплачен ли заказ';
COMMENT ON COLUMN orders.collecting_start_date IS 'Время начала сборки';
COMMENT ON COLUMN orders.collecting_end_date IS 'Время окончания сборки';
COMMENT ON COLUMN orders.courier_take_date IS 'Время, когда курьер забрал заказ';
COMMENT ON COLUMN orders.courier_delivered_date IS 'Время доставки клиенту';
COMMENT ON COLUMN orders.completed_date IS 'Финальное завершение заказа';


CREATE TABLE IF NOT EXISTS order_products (
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    amount NUMERIC(10,3) NOT NULL CHECK (amount > 0),
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),

    PRIMARY KEY (order_id, product_id),

    CONSTRAINT fk_op_order
        FOREIGN KEY (order_id) REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_op_product
        FOREIGN KEY (product_id) REFERENCES products(id)
        ON DELETE RESTRICT
);

ALTER TABLE order_products OWNER TO REPLICATION_GROUP;
ALTER TABLE order_products REPLICA IDENTITY FULL;

COMMENT ON TABLE order_products IS 'Состав заказа (товары внутри заказа)';
COMMENT ON COLUMN order_products.amount IS 'Количестов товара в заказе';
COMMENT ON COLUMN order_products.price IS 'Цена товара на момент добавления в заказ';

CREATE TABLE IF NOT EXISTS work_shifts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP,
    create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    close_date TIMESTAMP,
    courier_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('planned', 'active', 'closed')),
    close_reason VARCHAR(50) CHECK (
        close_reason IN ('successful_done', 'courier_didnt_come_out', 'cancelled_by_manager')
    ),

    CONSTRAINT fk_shift_courier
        FOREIGN KEY (courier_id) REFERENCES couriers(id)
        ON DELETE CASCADE
);

ALTER TABLE work_shifts OWNER TO REPLICATION_GROUP;
ALTER TABLE work_shifts REPLICA IDENTITY FULL;

COMMENT ON TABLE work_shifts IS 'Смены курьеров';
COMMENT ON COLUMN work_shifts.status IS 'Статус смены: planned / active / closed';
COMMENT ON COLUMN work_shifts.close_reason IS 'Причина закрытия смены';
