# Коннектор для чтения postgresql WAL и записи изменений в топики кафки
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: false
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: false
    database.hostname: {{ .Values.postgresql.fullNameOverride }}
    database.port: 5432
    database.dbname: delivery
    database.user: {{ .Values.postgresql.auth.username }}
    database.password: {{ .Values.postgresql.auth.password }}
    database.server.id: 184054
    topic.prefix: postgres.delivery
    # Схемы, изменения которых слушаем
    schema.include.list: public
    # параметр означает, что при первом запуске коннектора не будут отправлены данные, которые уже находились в базе, читаем только изменения
    snapshot.mode: no_data
    table.include.list: {{ .Values.tablesList }}
    # В кафку дробные значения пишутся как строки
    decimal.handling.mode: string
    # ~ 5 гигабайт, так как топики быстро переполняются
    topic.creation.default.retention.bytes: 5000000000
    topic.creation.default.replication.factor: 2  
    topic.creation.default.partitions: 10
    topic.creation.default.cleanup.policy: delete
    # Проверяем каждые 10 секунд
    log.retention.check.interval.ms: 10000