apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: false
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: false
    database.hostname: {{ .Values.postgresql.fullNameOverride }}
    database.port: 5432
    database.dbname: delivery
    database.user: {{ .Values.postgresql.auth.username }}
    database.password: {{ .Values.postgresql.auth.password }}
    database.server.id: 184054
    topic.prefix: postgres.delivery
    schema.include.list: public
    snapshot.mode: no_data
    table.include.list: {{ .Values.tablesList }}