apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  namespace: default
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: docker.io/mirdeorbit/debezium-connect:1.7.10
  replicas: 1
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi
  bootstrapServers: {{.Values.listeners.plain.host}}:{{.Values.listeners.plain.port}}
  groupId: connect-cluster
  offsetStorageTopic: connect-cluster-offsets
  configStorageTopic: connect-cluster-configs
  statusStorageTopic: connect-cluster-status
  logging:
    type: inline
    loggers:
      rootLogger.level: WARN
      logger.kafka.level: WARN
      logger.logcleaner.level: WARN
      logger.authorizer.level: WARN
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    cleanup.policy: compact
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1