# connector for listening changes from kafka postgresql topics and write it to clickhouse for 
# operational data store (ODS)
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: debezium-connector-clickhouse-cdc
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: com.clickhouse.kafka.connect.ClickHouseSinkConnector
  tasksMax: 1
  config:
    hostname: click-cdc-{{ .Values.clickhouse.fullNameOverride }}-headless.default.svc
    schemas.enable: false
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    # Слушаем топики с таким префиксом
    topics.regex: "^postgres.*"
    username: {{ .Values.authCredentials.username }}
    password: {{ .Values.authCredentials.password }}
    port: {{ .Values.clickhouse.containerPorts.http }}
    database: {{ .Values.cdcDatabase.name }}
    topic2TableMap: {{ .Values.topic2tableMap.cdc }}
    transforms: flatten
    transforms.flatten.type: org.apache.kafka.connect.transforms.Flatten$Value
    transforms.flatten.delimiter: "."
    # Объединяем ли сообщения из разных partition в один batch
    ignorePartitionsWhenBatching: false
    # Максимальное еоличесто записей, которое может быть передано в коннектор за один запрос
    # один цикл чтения из Kafka даст максимум 10000 сообщений.
    consumer.max.poll.records: 10000
    # Максимальный размер данных, который консьюмер может получить из одной партиции за один fetch.
    # Если сообщение больше — Kafka всё равно его отдаст.
    consumer.max.partition.fetch.bytes: 5242880
    # Kafka не отдаст данные, пока не накопится минимум 1MB сообщений.
    consumer.fetch.min.bytes: 1048576
    # Максимальное время ожидания Kafka, чтобы накопить fetch.min.bytes.
    consumer.fetch.max.wait.ms: 500