apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-0-kafka-debezium-cluster-kafka-debezium-node-pool-0-pv
  labels:
    type: local
spec:
  storageClassName: kafka-local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/minikube/kafka/replica0"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-1-kafka-debezium-cluster-kafka-debezium-node-pool-1-pv
  labels:
    type: local
spec:
  storageClassName: kafka-local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/minikube/kafka/replica1"


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-2-kafka-debezium-cluster-kafka-debezium-node-pool-2-pv
  labels:
    type: local
spec:
  storageClassName: kafka-local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/minikube/kafka/replica2"