
postgresql:
  nameOverride: postgres
  fullNameOverride: postgres

  image:
    debug: true
    repository: mirdeorbit/postgres-custom
    tag: "1.0"

  global:
    security:
      allowInsecureImages: true

  auth:
    postgresPassword: pass123
    username: wal_reader
    password: wal_reader_password123

  primary:
    existingConfigmap: "postgres-config"
    containerSecurityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: false
    initdb:
      user: postgres
      password: pass123
      scriptsConfigMap: postgres-initdb
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 4
        memory: 4Gi