apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  pg_hba.conf: |
    local all all scram-sha-256
    host all all 0.0.0.0/0 scram-sha-256
    local replication wal_reader trust   
    host replication wal_reader 127.0.0.1/32 trust   
    host replication wal_reader ::1/128 trust 
  postgresql.conf: |
    listen_addresses = '*'
    port = '5432'
    max_connections = '25000'
    wal_level = 'logical'
    fsync = 'on'
    max_wal_size = '400MB'
    archive_mode = 'on'
    archive_command = '/bin/true'
    max_wal_senders = 1
    max_replication_slots = 1
    logging_collector = 'on'
    log_directory = '/opt/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = 'false'
    log_disconnections = 'false'
    log_hostname = 'true'
    client_min_messages = 'error'
    include_dir = 'conf.d'
    pgaudit.log_catalog = 'off'
    hot_standby = 'off'
    shared_preload_libraries = 'decoderbufs'

