apiVersion: v1
name: postgres
version: 1.0.389
description: Chart for Postgres data source deploy
appVersion: "1.0.389"
deprecated: false
dependencies:
  - name: postgresql
    version: 18.2.6
    repository: https://charts.bitnami.com/bitnami