apiVersion: v1
name: click-cdc
version: 1.0.170
description: Chart for Clickhouse data source deploy
appVersion: "1.0.170"
deprecated: false
dependencies:
  - name: clickhouse
    version: 9.4.4
    repository: https://charts.bitnami.com/bitnami